In [1]:
import numpy as np
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

In [2]:
x = np.random.randint(1,100,(6,6))

In [3]:
print(x)

[[82 71 17 41 17 35]
 [38 60 15 84 69 63]
 [52 15 45 15 76 46]
 [78 58 17 24 30 34]
 [86  1  5 51 93 11]
 [68 83 38 33 66 61]]


In [4]:
x[0]

array([82, 71, 17, 41, 17, 35])

In [6]:
x[0,1]

71

In [7]:
x[:,4]

array([17, 69, 76, 30, 93, 66])

In [8]:
x[:,4]

array([17, 69, 76, 30, 93, 66])